import { createAsyncThunk, createSlice } from '@reduxjs/toolkit'
import { checkUser, createUser, signOut } from './authAPI'

const initialState = {
  loggedInUser: null,
  status: 'idle',
  error: null,
}

export const createUserAsync = createAsyncThunk(
  'user/createUser',
  async (userInfo,{ rejectWithValue}) => {
    try {
      const response = await createUser(userInfo)
      return response.data
    } catch (error) {
      console.log(error)
      return rejectWithValue(error.data)
    }
  }
)
export const checkUserAsync = createAsyncThunk(
  'user/checkUser',
  async (loginInfo, { rejectWithValue }) => {
    try {
      const response = await checkUser(loginInfo)
      return response.data
    } catch (error) {
      return rejectWithValue(error.data)
    }
  }
)
export const signOutAsync = createAsyncThunk('user/signOut', async (userId) => {
  const response = await signOut(userId)
  return response.data
})

export const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    resetError:(state)=>{
      state.error=null
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createUserAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(createUserAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        console.log(action.payload)
        state.loggedInUser = action.payload
      })
      .addCase(createUserAsync.rejected, (state, action) => {
        state.status = 'idle'
        state.error = action.payload
      })
      .addCase(checkUserAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(checkUserAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        state.loggedInUser = action.payload
      })
      .addCase(checkUserAsync.rejected, (state, action) => {
        state.status = 'idle'
        state.error = action.payload
      })
      .addCase(signOutAsync.pending, (state) => {
        state.status = 'loading'
      })
      .addCase(signOutAsync.fulfilled, (state, action) => {
        state.status = 'idle'
        state.loggedInUser = null
      })
  },
})

export const { resetError} = authSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.user.value)`
export const selectloggedInUser = (state) => state.auth.loggedInUser
export const selectError = (state) => state.auth.error

export default authSlice.reducer
